# Generated by Django 3.2.5 on 2021-08-03 07:51

import book_center.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCenterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('description', models.CharField(max_length=200, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('is_book_of_month', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[(1, 'Book of the Month'), (2, 'Book Fair'), (3, 'Author Meeting'), (4, 'Public Reading')], max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('event_image', models.ImageField(upload_to='')),
                ('event_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
