# Generated by Django 3.2.5 on 2021-08-07 21:40

import book_center.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCenterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('description', models.CharField(max_length=200, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('is_book_of_month', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('book_month', 'Book of the Month'), ('book_fair', 'Book Fair'), ('author_meeting', 'Author Meeting'), ('public_reading', 'Public Reading')], max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('event_image', models.ImageField(upload_to='events')),
                ('event_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
        migrations.CreateModel(
            name='BookCenterEventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_events.bookcenterevent')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Log',
            },
        ),
    ]
