# Generated by Django 3.2.5 on 2021-08-03 08:11

import book_center.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcenterevent',
            options={'verbose_name': 'Event'},
        ),
        migrations.RemoveField(
            model_name='bookcenterevent',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='bookcenterevent',
            name='category',
            field=models.CharField(choices=[('book_month', 'Book of the Month'), ('book_fair', 'Book Fair'), ('author_meeting', 'Author Meeting'), ('public_reading', 'Public Reading')], max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english]),
        ),
        migrations.AlterField(
            model_name='bookcenterevent',
            name='event_image',
            field=models.ImageField(upload_to='events'),
        ),
    ]
