# Generated by Django 3.2.5 on 2021-08-04 12:29

import book_center.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCenterBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('author', models.CharField(max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('image', models.ImageField(upload_to='books')),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookCenterDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(5)])),
                ('topics', models.CharField(max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('image', models.ImageField(upload_to='discussions')),
            ],
        ),
        migrations.CreateModel(
            name='BookCenterUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('last_name', models.CharField(blank=True, max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('bio', models.CharField(blank=True, max_length=200, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('profile_image', models.ImageField(default='profiles/default_profile_img.jpg', upload_to='profiles')),
                ('country', models.CharField(blank=True, choices=[('BG', 'Bulgaria'), ('UK', 'United Kingdom'), ('RO', 'Romania')], max_length=100)),
                ('city', models.CharField(blank=True, max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('twitter_account', models.CharField(blank=True, max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('facebook_account', models.CharField(blank=True, max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('instagram_account', models.CharField(blank=True, max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
