# Generated by Django 3.2.5 on 2021-07-30 13:13

import book_center.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCenterUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('last_name', models.CharField(blank=True, max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('profile_image', models.ImageField(default='profiles/default_profile_image.jpg', upload_to='profiles')),
                ('country', models.CharField(default='Bulgaria', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
