# Generated by Django 3.2.5 on 2021-08-02 19:29

import book_center.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcenteruserprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, validators=[book_center.utils.validators.validate_alphabet_characters_english]),
        ),
    ]
