# Generated by Django 3.2.5 on 2021-08-04 19:57

import book_center.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcenterbook',
            name='genre',
            field=models.CharField(blank=True, max_length=30, validators=[book_center.utils.validators.validate_alphabet_characters_english]),
        ),
    ]
