# Generated by Django 3.2.5 on 2021-08-05 06:59

import book_center.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc_profiles', '0002_bookcenterbook_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcenterdiscussion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookcenterdiscussion',
            name='topics',
        ),
        migrations.AddField(
            model_name='bookcenterdiscussion',
            name='description',
            field=models.CharField(default='say hello baby', max_length=200, validators=[book_center.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcenterdiscussion',
            name='topic',
            field=models.CharField(default='topic', max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_profiles.bookcenterdiscussion')),
            ],
        ),
    ]
