# Generated by Django 3.2.5 on 2021-08-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc_profiles', '0003_auto_20210805_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcenterdiscussion',
            name='author',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='bc_auth.bookcenteruser'),
            preserve_default=False,
        ),
    ]
