# Generated by Django 3.2.5 on 2021-08-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_profiles', '0005_alter_bookcenterdiscussion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncomment',
            name='discussion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bc_profiles.bookcenterdiscussion'),
        ),
    ]
