# Generated by Django 3.2.5 on 2021-08-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc_profiles', '0006_alter_discussioncomment_discussion'),
    ]

    operations = [

        migrations.AlterField(
            model_name='discussioncomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_profiles.bookcenterdiscussion'),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
