# Generated by Django 3.2.5 on 2021-08-06 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bc_profiles', '0007_auto_20210806_0724'),
    ]

    operations = [

        migrations.RenameField(
            model_name='discussioncomment',
            old_name='comment',
            new_name='body',
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
