# Generated by Django 3.2.5 on 2021-08-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc_profiles', '0008_auto_20210806_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='bookcenterdiscussion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
