# Generated by Django 3.2.5 on 2021-07-27 15:00

import book_center.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=50, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('message', models.CharField(max_length=500, validators=[book_center.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(10)])),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
