# Generated by Django 3.2.5 on 2021-07-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_contact', '0003_alter_contactformmodel_date_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'verbose_name': 'Contact Form'},
        ),
    ]
