# Generated by Django 3.2.5 on 2021-07-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcenteruser',
            name='username',
        ),
        migrations.AddField(
            model_name='bookcenteruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
