# Generated by Django 3.2.5 on 2021-08-07 19:13

import book_center.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCenterBlogPostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('last_name', models.CharField(max_length=20, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
            ],
            options={
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='BookCenterBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('text', models.TextField(max_length=500, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('slug', models.SlugField(unique=True, validators=[book_center.utils.validators.validate_alphabet_characters_english])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bc_blog.bookcenterblogpostauthor')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
        ),
    ]
